esphome:
  name: desk

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key
ota:
  - platform: esphome
    password:  !secret ota_password

wifi:
  ssid: !secret iot_ssid
  password: !secret iot_password
  # manual_ip:
  #   static_ip: 192.168.1.231
  #   gateway: 192.168.1.1
  #   subnet: 255.255.255.0
  ap:
    ssid: "Desk Fallback Hotspot"
    password: "u4RYMwIW7ww7"

uart:
  - id: uart_0
    rx_pin: GPIO03
    baud_rate: 19200
    # debug:
    #   direction: BOTH
    #   dummy_receiver: true
    #   sequence:
    #     - lambda: UARTDebug::log_string(direction, bytes);

external_components:
  - source: components

sensor:
  - platform: "wn17cm3"
    name: "Height"
    uart_id: uart_0

output:
  - platform: gpio
    inverted: true
    id: button_bit_up
    pin:
      number: GPIO12

  - platform: gpio
    inverted: true
    id: button_bit_down
    pin:
      number: GPIO14

  - platform: gpio
    inverted: true
    id: button_bit_1
    pin:
      number: GPIO27

  - platform: gpio
    inverted: true
    id: button_bit_2
    pin:
      number: GPIO26

  - platform: gpio
    inverted: true
    id: button_bit_3
    pin:
      number: GPIO25

  - platform: gpio
    inverted: true
    id: button_bit_4
    pin:
      number: GPIO33

  - platform: gpio
    inverted: true
    id: button_bit_m
    pin:
      number: GPIO32

button:
  # Recall Presets
  - platform: template
    id: move_desk_up
    name: "UP"
    icon: "mdi:numeric-1-box"
    on_press:
      - output.turn_on: button_bit_up
      - delay: 1s
      - output.turn_off: button_bit_up
  - platform: template
    id: move_desk_down
    name: "Down"
    icon: "mdi:numeric-1-box"
    on_press:
      - output.turn_on: button_bit_down
      - delay: 1s
      - output.turn_off: button_bit_down
  - platform: template
    id: preset_set
    name: "M"
    icon: "mdi:numeric-1-box"
    on_press:
      - output.turn_on: button_bit_m
      - delay: 1s
      - output.turn_off: button_bit_m
  - platform: template
    id: recall_preset_1
    name: "Preset 1"
    icon: "mdi:numeric-1-box"
    on_press:
      - output.turn_on: button_bit_1
      - delay: 1s
      - output.turn_off: button_bit_1
  - platform: template
    id: recall_preset_2
    name: "Preset 2"
    icon: "mdi:numeric-2-box"
    on_press:
      - output.turn_on: button_bit_2
      - delay: 1s
      - output.turn_off: button_bit_2
  - platform: template
    id: recall_preset_3
    name: "Preset 3"
    icon: "mdi:numeric-3-box"
    on_press:
      - output.turn_on: button_bit_3
      - delay: 1s
      - output.turn_off: button_bit_3
  - platform: template
    id: recall_preset_4
    name: "Preset 4"
    icon: "mdi:numeric-4-box"
    on_press:
      - output.turn_on: button_bit_4
      - delay: 1s
      - output.turn_off: button_bit_4

captive_portal:

logger:
  level: INFO